on:
  push:
    branches:
      - main
  pull_request:

name: Static Analysis

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Set your desired PHP version
          extensions: mbstring, dom, zip, intl

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: PHPStan
        run: php ./vendor/bin/phpstan analyse --level=max