on:
  push:
    branches:
      - main
  pull_request:

name: Static Analysis

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: PHPStan
        uses: OskarStark/phpstan-ga@1.13.0
        with:
          args: analyse src/ --level=10
