name: PHP Linting
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@latest
        with:
          verboseMode: true
          testMode: true
          configPath: "pint.json"
          pintVersion: 1.21
          onlyDirty: true